[package]
name = "llvmpipe_ci_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
tweak_shader = "0.5.0"
wgpu = "27.0.1"
bytemuck = { version = "1.14.0", features = ["derive"] }
pollster = "0.3.0"
image = "0.24.7"
rendiff = "0.2.1"
