name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: LLVMPipe
        run: |
          sudo apt-get update
          sudo apt-get install -y mesa-vulkan-drivers
      - name: Run tests
        env:
          LIBGL_ALWAYS_SOFTWARE: 1
          MESA_VK_WSI_PRESENT_MODE: immediate
        run: cargo test
